version: '3.4'

x-logging:
      &default-logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "5"

services:
  homer-docker:
    image: homer_vihat:1.0
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var_lib_mysql:/var/lib/mysql
    network_mode: "host"
    logging: *default-logging
